-- Seed 10 real SaaS projects as feature requests (5 per user)

-- User 1: nick@nickmartin.com
INSERT INTO public.pull_requests (user_id, title, url, description, stage, categories, focus_areas, questions, status, queue_position)
VALUES
  ('815e70f3-7a74-467e-a731-e90ad11890ef', 'Linear', 'https://linear.app', 'Project management tool built for modern software teams. Focuses on speed, keyboard shortcuts, and streamlined issue tracking with cycles and projects.', 'launched', ARRAY['SaaS'], ARRAY['UX/UI Design','Onboarding Flow','Performance'], ARRAY['Is the issue creation flow intuitive for new users?','How does the keyboard-first navigation feel compared to competitors?','Are cycles and projects easy to distinguish?'], 'open', nextval('public.pull_requests_queue_seq')),

  ('815e70f3-7a74-467e-a731-e90ad11890ef', 'Cal.com', 'https://cal.com', 'Open-source scheduling platform that lets users create booking pages, manage availability, and integrate with Google Calendar, Zoom, and other tools.', 'launched', ARRAY['SaaS'], ARRAY['Onboarding Flow','Integrations','Landing Page'], ARRAY['Is the initial calendar setup straightforward?','How clear is the availability configuration UI?','Does the booking page feel trustworthy to invitees?'], 'open', nextval('public.pull_requests_queue_seq')),

  ('815e70f3-7a74-467e-a731-e90ad11890ef', 'Resend', 'https://resend.com', 'Email API for developers that makes it easy to send transactional and marketing emails with a modern SDK and React Email integration.', 'mvp', ARRAY['SaaS','AI/ML'], ARRAY['Developer Experience','API Design','Documentation'], ARRAY['Is the SDK easy to integrate into an existing project?','How helpful are the error messages when something goes wrong?','Does the dashboard give enough visibility into email delivery status?'], 'open', nextval('public.pull_requests_queue_seq')),

  ('815e70f3-7a74-467e-a731-e90ad11890ef', 'Dub.co', 'https://dub.co', 'Open-source link management platform with built-in analytics, custom domains, and team collaboration for tracking marketing links.', 'launched', ARRAY['SaaS','Marketplace'], ARRAY['Analytics Dashboard','UX/UI Design','Pricing'], ARRAY['Is the link analytics dashboard easy to understand at a glance?','How intuitive is the custom domain setup process?','Does the free tier offer enough value to convert users?'], 'open', nextval('public.pull_requests_queue_seq')),

  ('815e70f3-7a74-467e-a731-e90ad11890ef', 'Trigger.dev', 'https://trigger.dev', 'Background jobs framework for TypeScript that lets developers write reliable long-running tasks with retries, scheduling, and observability built in.', 'prototype', ARRAY['SaaS'], ARRAY['Developer Experience','Documentation','Onboarding Flow'], ARRAY['Is the concept of triggers vs jobs clear from the docs?','How easy is it to go from zero to a running background job?','Does the dashboard provide enough debugging info when a job fails?'], 'open', nextval('public.pull_requests_queue_seq')),

-- User 2: nick@magloft.com
  ('326b3802-62a2-4457-a5d0-c2a28624d6e8', 'Cal AI', 'https://cal.ai', 'AI-powered scheduling assistant that handles meeting coordination through natural language, built on top of Cal.com.', 'mvp', ARRAY['SaaS','AI/ML'], ARRAY['AI/ML Features','UX/UI Design','Onboarding Flow'], ARRAY['Does the AI correctly interpret ambiguous scheduling requests?','How well does it handle timezone differences?','Is the fallback to manual scheduling smooth when AI fails?'], 'open', nextval('public.pull_requests_queue_seq')),

  ('326b3802-62a2-4457-a5d0-c2a28624d6e8', 'Documenso', 'https://documenso.com', 'Open-source alternative to DocuSign for digital document signing with a focus on transparency and self-hosting options.', 'launched', ARRAY['SaaS'], ARRAY['UX/UI Design','Security','Onboarding Flow'], ARRAY['Is the document signing flow clear for non-technical recipients?','How trustworthy does the signing experience feel?','Is the self-hosting setup well documented?'], 'open', nextval('public.pull_requests_queue_seq')),

  ('326b3802-62a2-4457-a5d0-c2a28624d6e8', 'Formbricks', 'https://formbricks.com', 'Open-source survey and experience management platform with in-app surveys, link surveys, and website pop-ups.', 'launched', ARRAY['SaaS'], ARRAY['UX/UI Design','Integrations','Analytics Dashboard'], ARRAY['Is the survey builder intuitive for non-developers?','How well do in-app surveys integrate without hurting page performance?','Are the response analytics actionable?'], 'open', nextval('public.pull_requests_queue_seq')),

  ('326b3802-62a2-4457-a5d0-c2a28624d6e8', 'Papermark', 'https://papermark.io', 'Open-source document sharing platform with built-in analytics for tracking who viewed your pitch decks, proposals, and documents.', 'mvp', ARRAY['SaaS'], ARRAY['Analytics Dashboard','UX/UI Design','Landing Page'], ARRAY['Does the viewer analytics dashboard provide useful engagement insights?','Is the document upload and sharing flow frictionless?','How does the viewing experience compare to traditional PDF sharing?'], 'open', nextval('public.pull_requests_queue_seq')),

  ('326b3802-62a2-4457-a5d0-c2a28624d6e8', 'Infisical', 'https://infisical.com', 'Secret management platform for teams to sync environment variables and secrets across infrastructure with audit logs and access controls.', 'launched', ARRAY['SaaS','AI/ML'], ARRAY['Developer Experience','Security','Onboarding Flow'], ARRAY['Is the initial setup for syncing secrets intuitive?','How clear are the access control and permission models?','Does the CLI integration feel natural in existing dev workflows?'], 'open', nextval('public.pull_requests_queue_seq'));
